### ISSUE TITLE
i want use this with laravel

### ISSUE THREAD

**Issue by vahidalvandi** [Kayoti/Vtiger-Webservices-HTTP_Request2#2]
hello dear, thank you for this project , i am laravel developer and i want use this with laravel if you work on it please help me . 
also i currently  use cloud version on vtiger.com do i can connect api it ?

**Comment by Kayoti** [comment]
> hello dear, thank you for this project , i am laravel developer and i want use this with laravel if you work on it please help me . also i currently use cloud version on vtiger.com do i can connect api it ?

I am working on a laravel version as well you can have a work around and add it as custom code on vtiger cloud you just add api key

**Comment by vahidalvandi** [comment]
@Kayoti  where is it repository ?
